#remote_theme: daattali/beautiful-jekyll@6.0.1
#theme: jekyll-theme-minimal
#theme: jekyll-theme-slate
#theme: jekyll-theme-midnight
#theme: jekyll-theme-cayman
#theme: jekyll-theme-dinky
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#theme: jekyll-theme-architect
title: jekyll's Github site
logo: https://pbs.twimg.com/profile_images/378800000795058910/d611cb4aa977700fa86848cf0e27e004_400x400.jpeg  
#logo: assets/img/logo.png
description: A place to share my notes
google_analytics:
show_downloads: false
show_tree: true
